version: '3.8'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/umanni
    depends_on:
      - postgres
      - redis
      - sidekiq

  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@example.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "5051:80"
    depends_on:
      - postgres

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  
  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - postgres
      - redis

volumes:
  redis:
  postgres: